"""added upvotes and priority score 

Revision ID: 08312326f1fc
Revises: b7019e03843d
Create Date: 2026-01-17 18:53:22.081220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08312326f1fc'
down_revision = 'b7019e03843d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvote_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('priority_score', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_column('priority_score')
        batch_op.drop_column('upvote_count')

    # ### end Alembic commands ###
