"""data cleanup + add FKs

Revision ID: 0f774b4c9380
Revises: 2a249827e233
Create Date: 2026-02-07 10:41:43.555136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f774b4c9380'
down_revision = '2a249827e233'
branch_labels = None
depends_on = None


def upgrade():
    # Data cleanup to satisfy forthcoming foreign keys
    conn = op.get_bind()

    # Ensure fallback IssueType exists
    unc_row = conn.execute(sa.text(
        "SELECT id FROM issue_types WHERE name = :name"
    ), {"name": "Uncategorized"}).fetchone()
    if not unc_row:
        conn.execute(sa.text(
            "INSERT INTO issue_types (name, base_severity) VALUES (:name, :severity)"
        ), {"name": "Uncategorized", "severity": 1})
        unc_row = conn.execute(sa.text(
            "SELECT id FROM issue_types WHERE name = :name"
        ), {"name": "Uncategorized"}).fetchone()
    uncategorized_id = unc_row[0]

    # Remap complaints with invalid issue_type_id to fallback
    conn.execute(sa.text(
        """
        UPDATE complaints c
        LEFT JOIN issue_types it ON c.issue_type_id = it.id
        SET c.issue_type_id = :fallback
        WHERE it.id IS NULL
        """
    ), {"fallback": uncategorized_id})

    # Ensure fallback Deleted User exists (for invalid user_id)
    del_row = conn.execute(sa.text(
        "SELECT id FROM users WHERE email = :email"
    ), {"email": "deleted_user@example.com"}).fetchone()
    if not del_row:
        conn.execute(sa.text(
            """
            INSERT INTO users (name, email, password_hash, role, area, state, phone_number, created_at, updated_at)
            VALUES (:name, :email, :password_hash, :role, :area, :state, :phone, NOW(), NOW())
            """
        ), {
            "name": "Deleted User",
            "email": "deleted_user@example.com",
            "password_hash": "deleted",
            "role": "citizen",
            "area": "unknown",
            "state": "unknown",
            "phone": None,
        })
        del_row = conn.execute(sa.text(
            "SELECT id FROM users WHERE email = :email"
        ), {"email": "deleted_user@example.com"}).fetchone()
    deleted_user_id = del_row[0]

    # Remap complaints with invalid user_id to Deleted User
    conn.execute(sa.text(
        """
        UPDATE complaints c
        LEFT JOIN users u ON c.user_id = u.id
        SET c.user_id = :deleted_id
        WHERE u.id IS NULL
        """
    ), {"deleted_id": deleted_user_id})

    # Null out invalid officer_id (column is nullable)
    conn.execute(sa.text(
        """
        UPDATE complaints c
        LEFT JOIN officers o ON c.officer_id = o.off_id
        SET c.officer_id = NULL
        WHERE c.officer_id IS NOT NULL AND o.off_id IS NULL
        """
    ))

    # Add foreign keys now that data is clean
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'officers', ['officer_id'], ['off_id'])
        batch_op.create_foreign_key(None, 'issue_types', ['issue_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
