"""added off id and user id

Revision ID: 2a249827e233
Revises: bfa8f8805ad1
Create Date: 2026-02-07 10:37:37.699927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a249827e233'
down_revision = 'bfa8f8805ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        # Skipping FK creation due to existing orphaned data; handle in later data-cleanup migration
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###
