"""sync models

Revision ID: 398daa649b97
Revises: 08312326f1fc
Create Date: 2026-01-18 22:02:08.028900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398daa649b97'
down_revision = '08312326f1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('base_severity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('points_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('formula_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_ledger_officer_id'), ['officer_id'], unique=False)

    op.create_table('sla_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('deadline_hours', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complaint_type', 'priority', name='uq_sla_rule')
    )
    with op.batch_alter_table('sla_rules', schema=None) as batch_op:
        batch_op.create_index('idx_sla_lookup', ['complaint_type', 'priority'], unique=False)

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_column('resolved_at')

    with op.batch_alter_table('sla_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_sla_lookup')

    op.drop_table('sla_rules')
    with op.batch_alter_table('points_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_ledger_officer_id'))

    op.drop_table('points_ledger')
    op.drop_table('issue_types')
    # ### end Alembic commands ###
