"""add foriegn key

Revision ID: 439994ea0a39
Revises: 991f82e0df2c
Create Date: 2026-02-13 15:56:56.827681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '439994ea0a39'
down_revision = '991f82e0df2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    existing_columns = [col['name'] for col in inspector.get_columns('officers')]
    existing_fks = inspector.get_foreign_keys('officers')

    has_ward_id_col = 'ward_id' in existing_columns
    has_ward_fk = any(
        fk.get('referred_table') == 'wards'
        and fk.get('constrained_columns') == ['ward_id']
        and fk.get('referred_columns') == ['ward_id']
        for fk in existing_fks
    )

    with op.batch_alter_table('officers', schema=None) as batch_op:
        if not has_ward_id_col:
            batch_op.add_column(sa.Column('ward_id', sa.Integer(), nullable=False))
        if not has_ward_fk:
            # Use a stable, explicit constraint name to allow idempotent checks
            batch_op.create_foreign_key(
                'fk_officers_ward_id_wards_ward_id',
                'wards', ['ward_id'], ['ward_id']
            )
        if 'area' in existing_columns:
            batch_op.drop_column('area')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    existing_columns = [col['name'] for col in inspector.get_columns('officers')]
    existing_fks = inspector.get_foreign_keys('officers')

    with op.batch_alter_table('officers', schema=None) as batch_op:
        if 'area' not in existing_columns:
            batch_op.add_column(sa.Column('area', mysql.VARCHAR(length=50), nullable=False))
        # Drop our explicitly named FK if present; otherwise attempt generic drop
        fk_names = [fk.get('name') for fk in existing_fks]
        if 'fk_officers_ward_id_wards_ward_id' in fk_names:
            batch_op.drop_constraint('fk_officers_ward_id_wards_ward_id', type_='foreignkey')
        else:
            # Fallback for unknown/auto-generated FK names
            batch_op.drop_constraint(None, type_='foreignkey')
        if 'ward_id' in existing_columns:
            batch_op.drop_column('ward_id')

    # ### end Alembic commands ###
