"""Add payer fields and razorpay ids to payments

Revision ID: 67c5fcf9a1ca
Revises: 332d326ec759
Create Date: 2026-02-27 11:47:29.332693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c5fcf9a1ca'
down_revision = '332d326ec759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payer_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('payer_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('razorpay_order_id')
        batch_op.drop_column('razorpay_payment_id')
        batch_op.drop_column('payer_email')
        batch_op.drop_column('payer_name')

    # ### end Alembic commands ###
