"""add wards table

Revision ID: 991f82e0df2c
Revises: e7b9e31d2515
Create Date: 2026-02-13 15:55:04.991275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991f82e0df2c'
down_revision = 'e7b9e31d2515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('polygon', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ward_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wards')
    # ### end Alembic commands ###
