"""sync complaints model changes

Revision ID: bfa8f8805ad1
Revises: 0e73df78ee0c
Create Date: 2026-02-07 10:33:57.753208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfa8f8805ad1'
down_revision = '0e73df78ee0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('image_path')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('image_path', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('resolved_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
