"""added image path

Revision ID: e7b9e31d2515
Revises: 1b4b1ed1c491
Create Date: 2026-02-07 12:11:54.165361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7b9e31d2515'
down_revision = '1b4b1ed1c491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points_ledger', schema=None) as batch_op:
        batch_op.alter_column('officer_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points_ledger', schema=None) as batch_op:
        batch_op.alter_column('officer_id',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
